# fix lineendings in Windows
init:
  - git config --global core.autocrlf input

environment:
  RUST_BACKTRACE: 1
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: i686-pc-windows-gnu

install:
  - appveyor-retry appveyor DownloadFile "https://static.rust-lang.org/rustup/dist/%TARGET%/rustup-init.exe" -FileName rustup-init.exe
  - rustup-init.exe -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

build: false

build_script:
  - rustc -V
  - cargo -V
  - cd "%APPVEYOR_BUILD_FOLDER%\rust\pact_matching"
  - cargo build
  - cargo test
  - cd "%APPVEYOR_BUILD_FOLDER%\rust\pact_mock_server"
  - cargo build
  - cargo test
  - cd "%APPVEYOR_BUILD_FOLDER%\rust\pact_mock_server_cli"
  - cargo build
  - cargo test
  - cd "%APPVEYOR_BUILD_FOLDER%\rust\pact_consumer"
  - cargo build
  - cargo test
  - cd "%APPVEYOR_BUILD_FOLDER%\rust\pact_verifier"
  - cargo build
  - cargo test
  - cd "%APPVEYOR_BUILD_FOLDER%\rust\pact_verifier_cli"
  - cargo build
  - cargo test

